Desktop version
Ashnaali3255/Portfolio-2 pull request #5
Opened 2023-01-18 14:06 UTC by Ashnaali3255

**Description**
For the fourth project in your portfolio website, you will:

Use media queries to make sure that your website displays correctly on desktop screens.

**General requirements**
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
Make sure that you used the correct ([Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
HTML/CSS requirements
Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
Project requirements
IMPORTANT NOTE: For each Microverse project, you need to create a separate pull request. [Read how to work with multiple pull requests in your one repository in the most efficient way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md).

You need to make sure that your desktop version looks like the one in the Figma design template that you chose. We include a screenshot of Template 1 below for reference, but you should use the template that you chose.

IMPORTANT NOTE some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in the Contact me or Get in touch sections). Please ignore this part of the design template and use only one input for the full name for all versions.

Desktop

- Use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: 768px or wider).

- In order to lay out the elements on the page you should use Grid and Flexbox.

- You don't need to implement any functionality that requires JavaScript.

- You must replicate the design as much as possible (e.g., font, colors, images, text, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2023-01-18 16:04 UTC, NduatiKagiri requested changes
Hi @Ashnaali3255 👋 ,

# CHANGES REQUIRED ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights ✔️ 
✅ GitHub Flow observed
✅ No Linters errors
✅ Good project description

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 16:04 UTC, NduatiKagiri commented on index.html
>       <section class="projects">
- [ ] You have wrong usage of the `section` element. Please note that you only have 4 sections in your page(the headline, work, about, and contact sections), and you should wrap each of them wholly in a `section` element, therefore having only 4 `section` elements. Please fix this and avoid mixing up `section` and `div` elements(using them interchangeably). This ensures good/smooth UX/UI.

2023-01-18 16:04 UTC, NduatiKagiri commented on index.html
> +          <h2>About<br>Myself</h2>
- [ ] I have noted that in some sections in your markup(this about section being one of them), you had the mobile design earlier, and you have now added the same code again in the same markup, for the desktop version. Please note that this is not how responsiveness works but uses the same markup, and renders it differently on different screen sizes. This is where CSS media queries come in and that is the approach you were supposed to use in this project milestone. Kindly refer to the lessons provided on your dashboard for better understanding, and apply the right approach in your project.

2023-01-18 16:04 UTC, NduatiKagiri commented on index.html
> - <section class="main-section">
- [ ] [ OPTIONAL ] It is always attractive when the headline of a web page fits in the screen's height perfectly, but your section does not fit, and has alot of unnecessary space above the heading.

    ![ashna1](https://user-images.githubusercontent.com/87394385/213201551-72822d15-05be-4271-8e3a-8117e07b7660.JPG)

-  Please consider minimizing the space above your content so that the headline section fits in the screen's height. You can achieve this by assigning it a height of (100vh - the height of the header) and then making sure that everything fits perfectly.

2023-01-18 16:04 UTC, NduatiKagiri commented on index.html
> +          <div class="proj-desc">
- [ ] Your work cards are overflowing to the right side, causing your page to have an unwanted horizontal scroll, and a bad look.

   ![ashna2](https://user-images.githubusercontent.com/87394385/213203557-3efb1efa-5702-4be5-87f9-70fa34d64afc.JPG)

-   Please apply the right width to your work cards, and also the right margins and padding to all the elements in the Works section. This will fix the overflow and the horizontal scroll.

2023-01-18 16:04 UTC, NduatiKagiri commented on style.css
> +    height: 50px !important;
- [ ] [ OPTIONAL ] According to [HTML/CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), overusing `!important` is highly discouraged since it may mean that some things are not implemented correctly, and the page might break when more elements are added. Please consider implementing every requirement correctly and avoid using this keyword.

2023-01-18 16:04 UTC, NduatiKagiri commented on style.css
> +  }
- [ ] As I mentioned about implementing responsivity, having multiple markups for different screens and using `display: none` for some markups in screens that you dont wish render them is a wrong approach. Kindly implement one markup with different stylings for different screens.

2023-01-19 11:21 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Ashnaali3255  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

✅ GitHub Flow observed
✅ No Linters errors
✅ Good project description

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 12:22 UTC, merged